Extend pivot table funtionality
360EntSecGroup-Skylar/excelize pull request #692
Opened 2020-08-19 12:57 UTC by EugeneAndrosovPaser

I am using your project and I have a need for advanced pivot table management.

Extensions and adaptations for our project are presented here. In order not to accompany and update both projects at once, I propose to make these changes to the master after the review and correction of comments.

2020-08-19 13:19 UTC, xuri requested changes
Thanks for your PR. I've left some comments. Please make sure to pass the CI.

2020-08-19 13:19 UTC, xuri commented on go.mod
> +module github.com/EugeneAndrosovPaser/excelize/v2
Please don't use private packages here.

2020-08-19 13:19 UTC, xuri commented on go.sum
> +github.com/360EntSecGroup-Skylar/excelize/v2 v2.2.0 h1:5DuRTdH6M8yPjvFfBkACVmuk7SoTzmaB8yM6KVqEhP8=
please kept original `go.mod` and `go.sum` files

2020-09-10 16:45 UTC, merged

2020-09-10 16:46 UTC, xuri commented
LGTM, thank you @EugeneAndrosovPaser.

2020-11-14 16:41 UTC, EugeneAndrosovPaser commented
Sorry for my absence. I had sick. Thank you for resolving my merge request.