Number format read fix
360EntSecGroup-Skylar/excelize pull request #741
Opened 2020-12-09 16:45 UTC by artiz

# PR Details

We are using excelize in our ETL project to parse variety XLSX files from our customers and had found that some XLSX files generated by ERP systems contain incorrect number format definitions that leads to panic in excelize library.

We have added safety check to avoid panic on XSLX file read

## How Has This Been Tested

Added new UT with example file

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-12-11 04:05 UTC, xuri requested changes
Hi @artiz, thanks for your PR. I've left some comments.

2020-12-11 04:05 UTC, xuri commented on crypt_test.go
> +	assert.EqualError(t, f.SaveAs(filepath.Join("test", "TestBadEncrypt.xlsx"), Options{Password: "password"}), "not support encryption currently")
I suggest to keep the spreadsheet name of them. In fact, I have a program offline that will batch verify the generated file with `Test` prefix can be opened correctly by Office applications :)

2020-12-11 20:43 UTC, artiz commented on cell.go
> +
got it, will refactor

2020-12-11 20:44 UTC, artiz commented on cell_test.go
> +	assert.NoError(t, err)
yep, copy-paste issue

2020-12-11 20:48 UTC, artiz commented on cell_test.go
> -	f.Styles.NumFmts = nil
will do

2020-12-12 08:17 UTC, merged

2020-12-12 08:17 UTC, xuri commented
LGTM, thanks for your PR.